site_name: Ch4zm of Hellmouth - Blaseball Data Witch
site_url: https://ch4zm.github.io
repo_name: ch4zm.github.io
repo_url: https://github.com/ch4zm/ch4zm.github.io

nav:
  - Homepage: index.md
  - Teaching: teaching.md
  - Famous Games:
    - Index: famous.md
    - SHOE THIEVES HAVE A BBQ: famous_thievesbbq.md
    - THE DEFLOWERING: famous_deflowering.md
    - THE SPANKING: famous_spanking.md
    - I HAD SIX BOOTS JUST A SECOND AGO: famous_sixboots.md
    - THE TALKERS HAVE LEFT THE BUILDING: famous_talkers.md
    - THE LOVERS HAVE A BBQ: famous_loversbbq.md
    - FIREFIGHERS EXTINGUISH THE JAZZ HANDS: famous_extinguish.md
    - GRAB THE TIGERS BY THE HORNE: famous_horne.md
    - DUDLEY SHAMES DUDLEY: famous_dudley.md
    - THE INCINERATION OF EMMETT INTERNET: famous_internet.md
    - THE MILLENNIALS ARE GROUNDED: famous_grounded.md
    - CAN SOMEONE PLEASE STOP THESE CRABS PART 1: famous_crabs1.md
    - A FRIENDLY GAME OF PING PONG: famous_pingpong.md
    - CAN SOMEONE PLEASE STOP THESE CRABS PART 2: famous_crabs2.md
    - THE INCINERATION OF RANDALL MARIJUANA: famous_marijuana.md
  - Streaks:
    - All Time Winning Streaks: wstreaks_alltime.md
    - Winning Streaks by Season:
      - Season 1 Winning Streaks: wstreaks_season1.md
      - Season 2 Winning Streaks: wstreaks_season2.md
      - Season 3 Winning Streaks: wstreaks_season3.md
      - Season 4 Winning Streaks: wstreaks_season4.md
      - Season 5 Winning Streaks: wstreaks_season5.md
      - Season 6 Winning Streaks: wstreaks_season6.md
    - Winning Streaks by Team:
      - Breath Mints Winning Streaks: wstreaks_team_breath_mints.md
      - Crabs Winning Streaks: wstreaks_team_crabs.md
      - Dale Winning Streaks: wstreaks_team_dale.md
      - Firefighters Winning Streaks: wstreaks_team_firefighters.md
      - Flowers Winning Streaks: wstreaks_team_flowers.md
      - Fridays Winning Streaks: wstreaks_team_fridays.md
      - Garages Winning Streaks: wstreaks_team_garages.md
      - Jazz Hands Winning Streaks: wstreaks_team_jazz_hands.md
      - Lovers Winning Streaks: wstreaks_team_lovers.md
      - Magic Winning Streaks: wstreaks_team_magic.md
      - Millennials Winning Streaks: wstreaks_team_millennials.md
      - Moist Talkers Winning Streaks: wstreaks_team_moist_talkers.md
      - Pies Winning Streaks: wstreaks_team_pies.md
      - Shoe Thieves Winning Streaks: wstreaks_team_shoe_thieves.md
      - Spies Winning Streaks: wstreaks_team_spies.md
      - Steaks Winning Streaks: wstreaks_team_steaks.md
      - Sunbeams Winning Streaks: wstreaks_team_sunbeams.md
      - Tacos Winning Streaks: wstreaks_team_tacos.md
      - Tigers Winning Streaks: wstreaks_team_tigers.md
      - Wild Wings Winning Streaks: wstreaks_team_wild_wings.md
    - All Time Losing Streaks: lstreaks_alltime.md
    - Losing Streaks by Season:
      - Season 1 Losing Streaks: lstreaks_season1.md
      - Season 2 Losing Streaks: lstreaks_season2.md
      - Season 3 Losing Streaks: lstreaks_season3.md
      - Season 4 Losing Streaks: lstreaks_season4.md
      - Season 5 Losing Streaks: lstreaks_season5.md
      - Season 6 Losing Streaks: lstreaks_season6.md
    - Losing Streaks by Team:
      - Breath Mints Losing Streaks: lstreaks_team_breath_mints.md
      - Crabs Losing Streaks: lstreaks_team_crabs.md
      - Dale Losing Streaks: lstreaks_team_dale.md
      - Firefighters Losing Streaks: lstreaks_team_firefighters.md
      - Flowers Losing Streaks: lstreaks_team_flowers.md
      - Fridays Losing Streaks: lstreaks_team_fridays.md
      - Garages Losing Streaks: lstreaks_team_garages.md
      - Jazz Hands Losing Streaks: lstreaks_team_jazz_hands.md
      - Lovers Losing Streaks: lstreaks_team_lovers.md
      - Magic Losing Streaks: lstreaks_team_magic.md
      - Millennials Losing Streaks: lstreaks_team_millennials.md
      - Moist Talkers Losing Streaks: lstreaks_team_moist_talkers.md
      - Pies Losing Streaks: lstreaks_team_pies.md
      - Shoe Thieves Losing Streaks: lstreaks_team_shoe_thieves.md
      - Spies Losing Streaks: lstreaks_team_spies.md
      - Steaks Losing Streaks: lstreaks_team_steaks.md
      - Sunbeams Losing Streaks: lstreaks_team_sunbeams.md
      - Tacos Losing Streaks: lstreaks_team_tacos.md
      - Tigers Losing Streaks: lstreaks_team_tigers.md
      - Wild Wings Losing Streaks: lstreaks_team_wild_wings.md
  - Interesting Games:
    - Shutouts:
      - All Time Shutouts: shutouts_alltime.md
      - Shutouts by Season:
        - Season 1 Shutouts: shutouts_season1.md
        - Season 2 Shutouts: shutouts_season2.md
        - Season 3 Shutouts: shutouts_season3.md
        - Season 4 Shutouts: shutouts_season4.md
        - Season 5 Shutouts: shutouts_season5.md
        - Season 6 Shutouts: shutouts_season6.md
      - Shutouts by Team:
        - Breath Mints Shutouts: shutouts_team_breath_mints.md
        - Crabs Shutouts: shutouts_team_crabs.md
        - Dale Shutouts: shutouts_team_dale.md
        - Firefighters Shutouts: shutouts_team_firefighters.md
        - Flowers Shutouts: shutouts_team_flowers.md
        - Fridays Shutouts: shutouts_team_fridays.md
        - Garages Shutouts: shutouts_team_garages.md
        - Jazz Hands Shutouts: shutouts_team_jazz_hands.md
        - Lovers Shutouts: shutouts_team_lovers.md
        - Magic Shutouts: shutouts_team_magic.md
        - Millennials Shutouts: shutouts_team_millennials.md
        - Moist Talkers Shutouts: shutouts_team_moist_talkers.md
        - Pies Shutouts: shutouts_team_pies.md
        - Shoe Thieves Shutouts: shutouts_team_shoe_thieves.md
        - Spies Shutouts: shutouts_team_spies.md
        - Steaks Shutouts: shutouts_team_steaks.md
        - Sunbeams Shutouts: shutouts_team_sunbeams.md
        - Tacos Shutouts: shutouts_team_tacos.md
        - Tigers Shutouts: shutouts_team_tigers.md
        - Wild Wings Shutouts: shutouts_team_wild_wings.md
      - Postseason Shutouts: shutouts_postseason.md
    - Blowouts:
      - All Time Blowouts: blowouts_alltime.md
      - Blowouts by Season:
        - Season 1 Blowouts: blowouts_season1.md
        - Season 2 Blowouts: blowouts_season2.md
        - Season 3 Blowouts: blowouts_season3.md
        - Season 4 Blowouts: blowouts_season4.md
        - Season 5 Blowouts: blowouts_season5.md
        - Season 6 Blowouts: blowouts_season6.md
      - Blowouts by Team:
        - Breath Mints Blowouts: blowouts_team_breath_mints.md
        - Crabs Blowouts: blowouts_team_crabs.md
        - Dale Blowouts: blowouts_team_dale.md
        - Firefighters Blowouts: blowouts_team_firefighters.md
        - Flowers Blowouts: blowouts_team_flowers.md
        - Fridays Blowouts: blowouts_team_fridays.md
        - Garages Blowouts: blowouts_team_garages.md
        - Jazz Hands Blowouts: blowouts_team_jazz_hands.md
        - Lovers Blowouts: blowouts_team_lovers.md
        - Magic Blowouts: blowouts_team_magic.md
        - Millennials Blowouts: blowouts_team_millennials.md
        - Moist Talkers Blowouts: blowouts_team_moist_talkers.md
        - Pies Blowouts: blowouts_team_pies.md
        - Shoe Thieves Blowouts: blowouts_team_shoe_thieves.md
        - Spies Blowouts: blowouts_team_spies.md
        - Steaks Blowouts: blowouts_team_steaks.md
        - Sunbeams Blowouts: blowouts_team_sunbeams.md
        - Tacos Blowouts: blowouts_team_tacos.md
        - Tigers Blowouts: blowouts_team_tigers.md
        - Wild Wings Blowouts: blowouts_team_wild_wings.md
      - Postseason Blowouts: blowouts_postseason.md
    - Underdog Wins:
      - All Time Underdog Wins: underdog_alltime.md
      - Underdog Wins by Season:
        - Season 1 Underdog Wins: underdog_season1.md
        - Season 2 Underdog Wins: underdog_season2.md
        - Season 3 Underdog Wins: underdog_season3.md
        - Season 4 Underdog Wins: underdog_season4.md
        - Season 5 Underdog Wins: underdog_season5.md
        - Season 6 Underdog Wins: underdog_season6.md
      - Underdog Wins by Team:
        - Breath Mints Underdog Wins: underdog_team_breath_mints.md
        - Crabs Underdog Wins: underdog_team_crabs.md
        - Dale Underdog Wins: underdog_team_dale.md
        - Firefighters Underdog Wins: underdog_team_firefighters.md
        - Flowers Underdog Wins: underdog_team_flowers.md
        - Fridays Underdog Wins: underdog_team_fridays.md
        - Garages Underdog Wins: underdog_team_garages.md
        - Jazz Hands Underdog Wins: underdog_team_jazz_hands.md
        - Lovers Underdog Wins: underdog_team_lovers.md
        - Magic Underdog Wins: underdog_team_magic.md
        - Millennials Underdog Wins: underdog_team_millennials.md
        - Moist Talkers Underdog Wins: underdog_team_moist_talkers.md
        - Pies Underdog Wins: underdog_team_pies.md
        - Shoe Thieves Underdog Wins: underdog_team_shoe_thieves.md
        - Spies Underdog Wins: underdog_team_spies.md
        - Steaks Underdog Wins: underdog_team_steaks.md
        - Sunbeams Underdog Wins: underdog_team_sunbeams.md
        - Tacos Underdog Wins: underdog_team_tacos.md
        - Tigers Underdog Wins: underdog_team_tigers.md
        - Wild Wings Underdog Wins: underdog_team_wild_wings.md
      - Postseason Underdog Wins: underdog_postseason.md
    - Shame Games:
      - All Time Shame Games: shame_alltime.md
      - Shame Games by Season:
        - Season 1 Shame Games: shame_season1.md
        - Season 2 Shame Games: shame_season2.md
        - Season 3 Shame Games: shame_season3.md
        - Season 4 Shame Games: shame_season4.md
        - Season 5 Shame Games: shame_season5.md
        - Season 6 Shame Games: shame_season6.md
      - Shame Games by Team:
        - Breath Mints Shame Games: shame_team_breath_mints.md
        - Crabs Shame Games: shame_team_crabs.md
        - Dale Shame Games: shame_team_dale.md
        - Firefighters Shame Games: shame_team_firefighters.md
        - Flowers Shame Games: shame_team_flowers.md
        - Fridays Shame Games: shame_team_fridays.md
        - Garages Shame Games: shame_team_garages.md
        - Jazz Hands Shame Games: shame_team_jazz_hands.md
        - Lovers Shame Games: shame_team_lovers.md
        - Magic Shame Games: shame_team_magic.md
        - Millennials Shame Games: shame_team_millennials.md
        - Moist Talkers Shame Games: shame_team_moist_talkers.md
        - Pies Shame Games: shame_team_pies.md
        - Shoe Thieves Shame Games: shame_team_shoe_thieves.md
        - Spies Shame Games: shame_team_spies.md
        - Steaks Shame Games: shame_team_steaks.md
        - Sunbeams Shame Games: shame_team_sunbeams.md
        - Tacos Shame Games: shame_team_tacos.md
        - Tigers Shame Games: shame_team_tigers.md
        - Wild Wings Shame Games: shame_team_wild_wings.md
      - Postseason Shame Games: shame_postseason.md
    - Maxed Out Games:
      - All Time Maxed Out Games: maxedout_alltime.md
      - Maxed Out Games by Season:
        - Season 1 Maxed Out Games: maxedout_season1.md
        - Season 2 Maxed Out Games: maxedout_season2.md
        - Season 3 Maxed Out Games: maxedout_season3.md
        - Season 4 Maxed Out Games: maxedout_season4.md
        - Season 5 Maxed Out Games: maxedout_season5.md
        - Season 6 Maxed Out Games: maxedout_season6.md
      - Maxed Out Games by Team:
        - Breath Mints Maxed Out Games: maxedout_team_breath_mints.md
        - Crabs Maxed Out Games: maxedout_team_crabs.md
        - Dale Maxed Out Games: maxedout_team_dale.md
        - Firefighters Maxed Out Games: maxedout_team_firefighters.md
        - Flowers Maxed Out Games: maxedout_team_flowers.md
        - Fridays Maxed Out Games: maxedout_team_fridays.md
        - Garages Maxed Out Games: maxedout_team_garages.md
        - Jazz Hands Maxed Out Games: maxedout_team_jazz_hands.md
        - Lovers Maxed Out Games: maxedout_team_lovers.md
        - Magic Maxed Out Games: maxedout_team_magic.md
        - Millennials Maxed Out Games: maxedout_team_millennials.md
        - Moist Talkers Maxed Out Games: maxedout_team_moist_talkers.md
        - Pies Maxed Out Games: maxedout_team_pies.md
        - Shoe Thieves Maxed Out Games: maxedout_team_shoe_thieves.md
        - Spies Maxed Out Games: maxedout_team_spies.md
        - Steaks Maxed Out Games: maxedout_team_steaks.md
        - Sunbeams Maxed Out Games: maxedout_team_sunbeams.md
        - Tacos Maxed Out Games: maxedout_team_tacos.md
        - Tigers Maxed Out Games: maxedout_team_tigers.md
        - Wild Wings Maxed Out Games: maxedout_team_wild_wings.md
      - Postseason Maxed Out Games: maxedout_postseason.md
    - Defensive Games:
      - All Time Defensive Games: defensive_alltime.md
      - Defensive Games by Season:
        - Season 1 Defensive Games: defensive_season1.md
        - Season 2 Defensive Games: defensive_season2.md
        - Season 3 Defensive Games: defensive_season3.md
        - Season 4 Defensive Games: defensive_season4.md
        - Season 5 Defensive Games: defensive_season5.md
        - Season 6 Defensive Games: defensive_season6.md
      - Defensive Games by Team:
        - Breath Mints Defensive Games: defensive_team_breath_mints.md
        - Crabs Defensive Games: defensive_team_crabs.md
        - Dale Defensive Games: defensive_team_dale.md
        - Firefighters Defensive Games: defensive_team_firefighters.md
        - Flowers Defensive Games: defensive_team_flowers.md
        - Fridays Defensive Games: defensive_team_fridays.md
        - Garages Defensive Games: defensive_team_garages.md
        - Jazz Hands Defensive Games: defensive_team_jazz_hands.md
        - Lovers Defensive Games: defensive_team_lovers.md
        - Magic Defensive Games: defensive_team_magic.md
        - Millennials Defensive Games: defensive_team_millennials.md
        - Moist Talkers Defensive Games: defensive_team_moist_talkers.md
        - Pies Defensive Games: defensive_team_pies.md
        - Shoe Thieves Defensive Games: defensive_team_shoe_thieves.md
        - Spies Defensive Games: defensive_team_spies.md
        - Steaks Defensive Games: defensive_team_steaks.md
        - Sunbeams Defensive Games: defensive_team_sunbeams.md
        - Tacos Defensive Games: defensive_team_tacos.md
        - Tigers Defensive Games: defensive_team_tigers.md
        - Wild Wings Defensive Games: defensive_team_wild_wings.md
      - Postseason Defensive Games: defensive_postseason.md

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css

theme:
  name: material
  palette:
    primary: amber
  favicon: img/favicon.png
  icon: 
    logo: fontawesome/solid/sun
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition

strict: true
