site_name: ch4zm of hellmouth
site_url: https://ch4zm.github.io

nav:
  - Home: index.md
  - Stuff: other.md

docs_dir: docs
site_dir: site

theme:
  name: material

markdown_extensions:
  - admonition

strict: true
